export enum EnvEnum {
  DEVELOPMENT = 'NEXT_PUBLIC_ENVIRONMENT',
  TOKEN_PREFIX = 'NEXT_PUBLIC_TOKEN_PREFIX',
  DB_NAME = 'NEXT_PUBLIC_DB_NAME',
  SECRET_TOKEN = 'NEXT_PUBLIC_SECRET_TOKEN',
  DB_URL = 'NEXT_PUBLIC_DB_URL',
  EXPIRATION_TOKEN = 'NEXT_PUBLIC_EXPIRATION_TOKEN',
}
