export enum EnvEnum {
  DEVELOPMENT = 'NEXT_PUBLIC_ENVIRONMENT',
  TOKEN_PREFIX = 'NEXT_PUBLIC_TOKEN_PREFIX',
  DB_NAME = 'NEXT_PUBLIC_DB_NAME',
  SECRET_TOKEN = 'NEXT_PUBLIC_SECRET_TOKEN',
  DB_URL = 'NEXT_PUBLIC_DB_URL',
  EXPIRATION_TOKEN = 'NEXT_PUBLIC_EXPIRATION_TOKEN',
  TOKEN_TEMP = 'NEXT_PUBLIC_TOKEN_TEST',
  PUBLIC_STRIPE = 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY',
  SECRET_STRIPE = 'NEXT_PUBLIC_STRIPE_SECRET_KEY',
  PRODUCTION_URL = 'NEXT_PUBLIC_PRODUCTION_URL',
}
